#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /index
    controller: App\Controller\indexController::index

user:
    path: /user
    controller: App\Controller\UserController::user

cotact:
    path: /contact
    controller: App\Controller\ContactController::contact