#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
    path: /hello-word
    controller: App\Controller\HelloWorldController::sayHello

index:
    path: /
    controller: App\Controller\indexController::index

user:
    path: /user
    controller: App\Controller\userController::user

user_edit:
    path: /user_edit
    controller: App\Controller\userEditController::userEdit