#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /index
    controller: App\Controller\indexController::index

api:
    path: /api/{id}/edit
    controller: App\Controller\ImputationController::apiedit

apiinew:
    path: /apii/new
    controller: App\Controller\ImputController::apinew

apiiedit:
    path: /apii/edit
    controller: App\Controller\ImputController::apiedit

apiidelete:
    path: /apii/delete
    controller: App\Controller\ImputController::apidelete
    
user:
    path: /user
    controller: App\Controller\UserController::user

imput:
    path: /imput
    controller: App\Controller\ImputController::ajaxAction

