#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
    path: /hello-word
    controller: App\Controller\HelloWorldController::sayHello

index:
    path: /
    controller: App\Controller\indexController::index

user:
    path: /user1
    controller: App\Controller\user1Controller::user

user_edit1:
    path: /user1_edit
    controller: App\Controller\userEdit1Controller::userEdit1