#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\indexController::index

user:
    path: /user1
    controller: App\Controller\UserController::user