#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /index
    controller: App\Controller\indexController::index

user:
    path: /user
    controller: App\Controller\UserController::user

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::calendar